source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

gem "rails", "~> 7.0.8"
gem "sprockets-rails"
gem 'jquery-rails'
gem "sqlite3", "~> 1.4"
gem "puma", "~> 5.0"

gem "importmap-rails"

gem "turbo-rails"

gem 'faraday'  
group :test do
  gem 'rails-controller-testing'
  gem 'guard-rspec'                 
end

gem "stimulus-rails"

gem "jbuilder"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console"
end

gem 'haml'
group :development, :test do
    gem 'byebug'
end
